### ISSUE TITLE
ccleMAEO.R calls nonexistent function makeRangedSummarizedExperimentFromDataFrame

### ISSUE THREAD

**Issue by vjcitn** [waldronlab/MultiAssayExperiment-CCLE#10]
makeRangedSummarizedExperimentFromDataFrame ... i can't find it

**Comment by lwaldron** [comment]
Looks like this should now be `SummarizedExperiment::makeSummarizedExperimentFromDataFrame()`?

**Comment by LiNk-NY** [comment]
Hi Vince and Levi, @vjcitn @lwaldron 
This is a bit tricky since to create the `rowRanges` part of the object, you would have to use `makeGRangesListFromDataFrame` and then use `makeSummarizedExperimentFromDataFrame` to create the `SummarizedExperiment` object. 
Please see the referenced commit. 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Please see new code in `R/ccleMAEO.R` for creating the object. 
3d0df8cb024d2124ccba8ffdbc022b982871f987
